// Generated by CoffeeScript 1.6.1
(function() {
  var Upload, fs, path, util, winston;

  fs = require("fs");

  winston = require("winston");

  path = require("path");

  util = require("util");

  Upload = (function() {
      function Upload(config, fileId, uid, fileExt) {
      this.fileId = fileId;
      this.fileExt = fileExt;
      this.uid = uid;
      this.filePath = path.join(config.files, fileId);
      this.infoPath = path.resolve("" + this.filePath + ".json");
      this.mdPath   = path.resolve("" + this.filePath + "_metadata.json");
      this.info = null;
    }

    Upload.prototype.create = function(finalLength, metadata) {
      var info;
      try {
        fs.closeSync(fs.openSync(this.filePath, 'w'));
      } catch (error) {
        winston.error(util.inspect(error));
        return {
          error: [500, "Create Failed"]
        };
      }
      try {
        info = {
          uid: this.uid || 'unknown',
	  fileId: this.fileId,
	  fileExt: this.fileExt || '.unknown',
          finalLength: finalLength,
          state: "created",
          createdOn: Date.now(),
          offset: 0
        };
        fs.writeFileSync(this.infoPath, JSON.stringify(info));
        this.info = info;
      } catch (error) {
        winston.error(util.inspect(error));
        return {
          error: [500, "Create Failed - Metadata"]
        };
      }
      try {
        fs.writeFileSync(this.mdPath, metadata);
      } catch (error) {
        winston.error(util.inspect(error));
        return {
          error: [500, "Create Failed - POST Body"]
        };
      }
      return {
        info: this.info
      };
    };

    Upload.prototype.save = function( callback ) {
	// winston.debug( "In save, br=" + this.info.offset + ", fl=" + this.info.finalLength );
	try {
            fs.writeFileSync(this.infoPath, JSON.stringify(this.info));
	} catch (error) {
            winston.error(util.inspect(error));
            return {
		error: [500, "Save Failed - Metadata"]
            };
	}
	if ( (this.info.offset == this.info.finalLength) && callback )
            callback()
	
	Info = {
            info: {
		fileId: this.info.fileId,
		finalLength: this.info.finalLength,
		state: this.info.state,
		createdOn: this.info.createdOn,
		offset: this.info.offset,
		patchedOn: this.info.patchedOn,
		bytesReceived: this.info.bytesReceived
	    }
	};
	return Info
    };

    Upload.prototype.load = function() {
      var stat;
      if (!fs.existsSync(this.filePath)) {
        return {
          error: [404, "File Not Found"]
        };
      }
      try {
        this.info = require(this.infoPath);
      } catch (error) {
        winston.error(util.inspect(error));
        return {
          error: [404, "Not Found - Metadata"]
        };
      }
      try {
        stat = fs.statSync(this.filePath);
        this.info.offset = stat.size;
      } catch (e) {
        winston.error("file error " + fileId + " " + (util.inspect(e)));
        return {
          error: [500, "File Load Error"]
        };
      }
      return {
        info: this.info
      };
    };

    Upload.prototype.stream = function() {
      return fs.createReadStream(this.filePath);
    };

    return Upload;

  })();

    exports.Upload = function(config, fileId, uid, fileExt) {
	return new Upload(config, fileId, uid, fileExt);
  };

}).call(this);
